[versions]
kotlin = "2.2.10"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlinpoet = "2.2.0"

java = "17"

ktor = "3.2.3"
kafka = "4.0.0"
kaftor = "0.2.2"

grpc = "1.78.0"
grpc-stub = "1.5.0"
protobuf = "4.33.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

gradleup-tapmoc = { id = "com.gradleup.tapmoc", version = "0.3.0" }

vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

charleskorn-kaml = { module = "com.charleskorn.kaml:kaml", version = "0.93.0" }
pearx-kasechange = { module = "net.pearx.kasechange:kasechange-jvm", version = "1.4.1" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }

# Code Generation Dependencies

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# Runtime Dependencies

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
kaftor = { module = "org.cufy.kaftor:kaftor", version.ref = "kaftor" }

protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }

grpc-api = { module = "io.grpc:grpc-api", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-stub" }
