[versions]
kotlin = "2.2.10"
kotlinx-serialization = "1.9.0"
kotlinpoet = "2.2.0"

java = "17"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

gradleup-tapmoc = { id = "com.gradleup.tapmoc", version = "0.3.0" }

vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

charleskorn-kaml = { module = "com.charleskorn.kaml:kaml", version = "0.93.0" }
pearx-kasechange = { module = "net.pearx.kasechange:kasechange-jvm", version = "1.4.1" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }

# Code Generation Dependencies

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# Client and Server Dependencies

ktor-server-core = { module = "io.ktor:ktor-server-core", version = "3.2.3" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version = "3.2.3" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version = "4.0.0" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version = "4.0.0" }

kaftor = { module = "org.cufy.kaftor:kaftor", version = "0.2.2" }
josekt = { module = "org.cufy.josekt:josekt", version = "0.1.2" }
extkt-json = { module = "org.cufy.extkt:extkt-json", version = "0.1.4" }
extkt-crypto = { module = "org.cufy.extkt:extkt-crypto", version = "0.1.4" }
